image: debian
sources:
  - https://git.sr.ht/~dctrud/clair-singularity
tasks:
  - setup: |
      cd clair-singularity
      bash build_scripts/travis_singularity.sh
      pip install flake8 pytest pytest-cov pytest-flake8 python-coveralls
  - test: |
      cd clair-singularity
      bash build_scripts/travis_tests.sh

