sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --only-binary=numpy,scipy,scikit-learn numpy scipy scikit-learn
  - pip install flake8 pytest pytest-cov pytest-flake8
  - python setup.py install
script: pytest --cov --flake8
