sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - wget -O- http://neuro.debian.net/lists/trusty.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt-get -qq update
  - sudo apt-get install -y singularity-container
install:
  - pip install --only-binary=numpy,scipy,scikit-learn,pandas numpy scipy scikit-learn pandas
  - pip install flake8 pytest pytest-cov pytest-flake8
  - pip install python-coveralls
  - python setup.py install
script:
  - pytest tests/ --cov clair_singularity --cov-report term-missing
after_success:
  - coveralls

